name: DoAn

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/DoAn
            git fetch --all
            git checkout production
            git pull
            npm install
            npm run build
            pm2 reload all
